# Generated by Django 5.0.14 on 2026-05-14 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('categories', models.JSONField(default=list)),
                ('lead_time', models.IntegerField(default=2)),
                ('payment_terms', models.CharField(default='Net 30', max_length=100)),
                ('rating', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Under Review', 'Under Review'), ('Suspended', 'Suspended')], default='Active', max_length=20)),
                ('since', models.DateField(auto_now_add=True)),
                ('on_time_rate', models.IntegerField(default=0)),
                ('quality_score', models.IntegerField(default=0)),
                ('fill_rate', models.IntegerField(default=0)),
                ('avg_response', models.CharField(default='—', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('delivered', 'Delivered'), ('late', 'Late'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('items', models.JSONField(default=list)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.branch')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='supply_chain.vendor')),
            ],
        ),
    ]
