# Generated by Django 5.0.14 on 2026-05-14 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('received_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('discrepancy', 'Discrepancy')], default='pending', max_length=20)),
                ('match_status', models.CharField(default='3-WAY MATCH COMPLETE', max_length=100)),
                ('match_results', models.JSONField(default=dict)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='supply_chain.purchaseorder')),
            ],
        ),
    ]
